apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brikko-studio-home-pvc
  labels:
    app: brikko-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
