export const browserCoreExamples = [
  "brikko-studio browser status",
  "brikko-studio browser start",
  "brikko-studio browser start --headless",
  "brikko-studio browser stop",
  "brikko-studio browser tabs",
  "brikko-studio browser open https://example.com",
  "brikko-studio browser focus abcd1234",
  "brikko-studio browser close abcd1234",
  "brikko-studio browser screenshot",
  "brikko-studio browser screenshot --full-page",
  "brikko-studio browser screenshot --ref 12",
  "brikko-studio browser snapshot",
  "brikko-studio browser snapshot --format aria --limit 200",
  "brikko-studio browser snapshot --efficient",
  "brikko-studio browser snapshot --labels",
];

export const browserActionExamples = [
  "brikko-studio browser navigate https://example.com",
  "brikko-studio browser resize 1280 720",
  "brikko-studio browser click 12 --double",
  "brikko-studio browser click-coords 120 340",
  'brikko-studio browser type 23 "hello" --submit',
  "brikko-studio browser press Enter",
  "brikko-studio browser hover 44",
  "brikko-studio browser drag 10 11",
  "brikko-studio browser select 9 OptionA OptionB",
  "brikko-studio browser upload /tmp/brikko-studio/uploads/file.pdf",
  'brikko-studio browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "brikko-studio browser dialog --accept",
  'brikko-studio browser wait --text "Done"',
  "brikko-studio browser evaluate --fn '(el) => el.textContent' --ref 7",
  "brikko-studio browser console --level error",
  "brikko-studio browser pdf",
];
